# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=LBreakout2
Version=2.5.1
Main=LBreakout2.exe
Description=It is a breakout-style arcade game in the manner of Arkanoid.

[Settings]
Item1=lgames
Item2=lbreakout2.hscr