# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=ImgBurn
Version=2.5.8.0
Main=ImgBurn.exe
Description=It writes most types of CD/DVD image files to physical media.

[Settings]
Item1=Settings
Item2=ImgBurn.ini