# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=IrfanView
Version=4.41
Main=IrfanView.exe
Description=It is an image viewer with support for a very large number of image formats, including animated GIF, multi-page TIFF and multiple ICO files.

[Settings]
Item1=i_view32.ini