# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Audacity
Version=2.1.1 + extra
Main=Audacity.exe
Description=It is an easy-to-use audio editor and recorder with a wide range of features.

[Settings]
Item1=Portable Settings
Item2=lame_enc.dll