# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Eigenmath
Version=137
Main=Eigenmath.exe
Description=It is a symbolic calculator that will offer you many solutions for math problems.

[Settings]
Item1=0