# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=FreeCommander XE
Version=2015.1.0.685
Main=FreeCommander.exe
Description=It is a dual-pane file manager with many features like a built-in file viewer, archive support, folder comparison, file search and more.

[Settings]
Item1=fcStart.ini
Item2=SETTINGS