# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=FooBillard
Version=3.0
Main=foobillard.exe
Description=It is a powerful 3D billard game.

[Settings]
Item1=0