# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=PhotoFiltre
Version=7.2.1
Main=PhotoFiltre7.exe
Description=It is a complete image retouching program.

[Settings]
Item1=PhotoFiltre.ini
Item2=PhotoFiltreDialogs.ini