# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=PDFTK Builder
Version=3.9.4
Main=PDFTK Builder.exe
Description=It is a tool to make some operations on PDF files: collate, split, background, decrypt and password protection.

[Settings]
Item1=0