# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=System Explorer
Version=5.5.0
Main=System Explorer.exe
Description=It is more than a simple Task Manager replacement, it offers detailed informations about Tasks, Processes, Modules, Startups, IE Addons, Uninstallers, Windows, Services, Drivers, Connections, Opened Files and much more.

[Settings]
Item1=config.ini