# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Tomahawk PDF+
Version=3.1
Main=TPdfPlus.exe
Description=It is a full-featured word processor for RTF, TXT and other file formats, with built-in PDF export capability.

[Settings]
Item1=Pdf Conversion
Item2=TPdfPlus.ini