# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=SumatraPDF
Version=3.1.1
Main=SumatraPDF.exe
Description=It reads a variety of document formats including PDF, MOBI, XPS, DjVu, CHM, CBZ and CBR.

[Settings]
Item1=symbols
Item2=sumatrapdfprefs.dat
Item3=SumatraPDF-settings.txt