# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Pawn2
Version=2.86
Main=Pawn.exe
Description=It is a chess program with an AI engine that is more suited for beginners to the game.

[Settings]
Item1=pawn.cfg