# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Revo Uninstaller
Version=1.95
Main=Revo Uninstaller.exe
Description=It helps you uninstall and remove any unwanted application installed on your computer.

[Settings]
Item1=settings.ini