# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Bricks '2000
Version=1.1a
Main=Bricks.exe
Description=It is a simple Tetris remake.

[Settings]
Item1=Bricks.dat
Item2=Bricks.ini