# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Typhoon 2001
Version=3992
Main=typhoon.exe
Description=It is a remake of the famous classic game Tempest.

[Settings]
Item1=typhoon.cfg