# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Notepad++
Version=6.8.8
Main=Notepad++.exe
Description=It is a source code editor which supports several programming languages running under the Microsoft Windows environment.

[Settings]
Item1=config.xml
Item2=session.xml
Item3=shortcuts.xml
Item4=stylers.xml