# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Portable Puzzles
Version=2.7 r20151207
Main=Portable Puzzles.exe
Description=It is a special collection of 39 games like MineSweeper, Sudoku, Ponti, Domino, Master-Mind and many others.

[Settings]
Item1=0