# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=BulkFileChanger
Version=1.35
Main=BulkFileChanger.exe
Description=It is a small utility to change file properties (time/date/hidden/read-only, etc), export file list, or copy/move files to another location.

[Settings]
Item1=BulkFileChanger.cfg