# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=FastStone Image Viewer
Version=5.5
Main=FSViewer.exe
Description=It is an image browser, viewer, editor and converter that supports many editing features.

[Settings]
Item1=FSSettings.db
Item2=FSViewer.db