# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=7-Zip Portable
Version=15.12
Main=7-ZipPortable.exe
Description=It is a popular file archiver that allow you to work with compressed 7z, ZIP, GZIP, BZIP2, TAR, RAR files and more.

[Settings]
Item1=Data