# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=FastStone Photo Resizer
Version=3.5
Main=FSResizer.exe
Description=It is a batch image converter/resizer that enables users to convert, rename, resize, crop, rotate and more.

[Settings]
Item1=FSResizerSettings.db