# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Converber
Version=2.3.1
Main=Converber.exe
Description=It is a unit converter that supports more than 1200 various units of measure in 32 categories.

[Settings]
Item1=Preferences.ini