# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=AbiWord Portable
Version=2.8.6
Main=AbiWordPortable.exe
Description=It is a lightweight word processor that supports many document types including Microsoft Word, Word Perfect, Open Document (OpenOffice.org), Office Open XML (MS Word 2007), RTF, HTML, Palm and more.

[Settings]
Item1=Data