# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Uno
Version=1.6
Main=Uno.exe
Description=It is a simple computer version of the card game Uno.

[Settings]
Item1=0