# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=PNotes
Version=9.3.0
Main=PNotes.exe
Description=It is a light-weight, flexible, skinnable manager of virtual notes on your desktop.

[Settings]
Item1=data
Item2=Notes.ini