# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Sokoban
Version=3.0.1.0
Main=Sokoban.exe
Description=It is a good and famous Japanese puzzle game.

[Settings]
Item1=settings.ini