; ********************************************************************************
; Configuration file for i2pdf 1.0.46
; You should not manually edit this file, unless you know what you are doing, but
; you can safely delete it if you want to restore all settings to factory defaults.
; ********************************************************************************
[PDF creation]
JpgCompression = 1
JpgQuality = 8
ImageScaling = 100
ResizeOnlyIfWider = 0
EnlargeToFit = 0
PaperOrientation = 1
PaperFormat = 5
PdfStartup = 1
KeepAspect = 1
DisplayHeader = 0
HeaderFontSize = 10
HeaderDisplayWhat = 1
HeaderDisplayWhere = 1
HeaderDisplayAlign = 1
SaveAuthor = 0
SaveTitle = 0
[Thumbnail]
ThumbLocked = 1
ThumbSide = 2
ThumbSize = 2
ThumbColor = 1
[General]
StayOnTop = 0
RememberWinPos = 0
ShowThumbs = 0
RememberLastDirectory = 1
SaveSameDirAsFiles = 0
ClearBeforeDrop = 0
ShowOptions = 1
ShowFullPath = 0
SortAfterDrop = 1
OpenPdf = 0
OpenDir = 1
Confirmations = 1
MemoryLoad = 1
ShowSizeCondensed = 1
SortIncludingPath = 0
Preprocessing = 1
DocTitleFromFileName = 0
DeleteLogIfSuccessful = 0
EnableSubFolders = 0
JpgNoRecompression = 0
