# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=i2pdf
Version=1.0.46
Main=i2pdf.exe
Description=It is a fast and compact application built to create Adobe PDF documents from a collection of images.

[Settings]
Item1=i2pdf.ini