# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Gui Checkers
Version=1.05+
Main=Gui Checkers.exe
Description=It is a simple checkers game.

[Settings]
Item1=0