# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=PDF-XChange Viewer
Version=2.5.315.0
Main=PDFXCview.exe
Description=It is a fast and powerful PDF viewer that supports also advanced features like annotations.

[Settings]
Item1=Settings.dat