# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Q-Dir
Version=6.22
Main=Q-Dir.exe
Description=It is a quad-pane file explorer that is capable of displaying 4 Explorer panes simultaneously.

[Settings]
Item1=Favoriten
Item2=Q-Dir.ini