# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=FastStone Capture
Version=5.3
Main=FSCapture.exe
Description=It is a powerful, flexible and intuitive screen-capture utility.

[Settings]
Item1=fsc.db
Item2=TBSettings.db