# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=ReNamer Lite
Version=6.3
Main=ReNamer.exe
Description=It is a small and flexible file renaming tool that offers all the standard renaming procedures.

[Settings]
Item1=Presets
Item2=ReNamer.ini