# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Mines-Perfect
Version=1.4.0
Main=Mines-Perfect.exe
Description=It is an improved remake of MineSweeper.

[Settings]
Item1=mineperf.ini