# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=CurrProcess
Version=1.13
Main=CurrProcess.exe
Description=It displays the list of all processes currently running on your system.

[Settings]
Item1=CurrProcess.cfg