# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Othello
Version=3.0
Main=Othello.exe
Description=It is a very simple and intuitive clone of Othello.

[Settings]
Item1=othello.ini