# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Notepad2
Version=4.2.25
Main=Notepad2.exe
Description=It is a small and fast text editor with syntax highlighting for HTML and other common languages.

[Settings]
Item1=Notepad2.ini