# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=Everything Portable
Version=1.3.4
Main=Everything.exe
Description=It is a small and fast indexing search program.

[Settings]
Item1=Everything.db
Item2=Everything.ini