# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=LC ISO Creator
Version=1.1
Main=LC ISO Creator.exe
Description=It creates ISO files from CD/DVD, which is a great way to backup or archive your CD/DVD discs.

[Settings]
Item1=0