# Lupo PenSuite Application Info
# This ini is used to manage software updates

[Software]
Name=foobar2000
Version=1.3.9
Main=foobar2000.exe
Description=It is an audio player with low memory footprint and native support for several popular audio formats.

[Settings]
Item1=configuration
Item2=index-data
Item3=playlists
Item4=theme.fth